apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-demo
  annotations:
    argocd.argoproj.io/tracking-id: nginx:/Service:nginx-demo/nginx
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false" # internet-facing
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
